"""Incidencias

Revision ID: 5ea269957a55
Revises: f1b9e103400d
Create Date: 2025-10-20 17:29:16.624242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea269957a55'
down_revision = 'f1b9e103400d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_datetime', sa.DateTime(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reporter_name', sa.String(length=120), nullable=False),
    sa.Column('reporter_role', sa.String(length=80), nullable=True),
    sa.Column('reporter_email', sa.String(length=120), nullable=False),
    sa.Column('reporter_phone', sa.String(length=20), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('incident_datetime', sa.DateTime(), nullable=False),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('environment_conditions', sa.Text(), nullable=True),
    sa.Column('affected_persons', sa.Text(), nullable=True),
    sa.Column('injuries', sa.Text(), nullable=True),
    sa.Column('witnesses', sa.Text(), nullable=True),
    sa.Column('equipment_involved', sa.String(length=255), nullable=True),
    sa.Column('property_damage', sa.Text(), nullable=True),
    sa.Column('corrective_actions', sa.Text(), nullable=False),
    sa.Column('emergency_services_contacted', sa.Boolean(), nullable=True),
    sa.Column('emergency_details', sa.String(length=255), nullable=True),
    sa.Column('root_cause', sa.String(length=255), nullable=True),
    sa.Column('preventive_actions', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('attachment_path', sa.String(length=255), nullable=True),
    sa.Column('evidence_comment', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('responsible_user_id', sa.Integer(), nullable=True),
    sa.Column('closure_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_reports')
    # ### end Alembic commands ###
