"""Presupuestos

Revision ID: fe1f9266fa50
Revises: 4eed0dfa1a21
Create Date: 2025-10-24 15:13:52.207368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1f9266fa50'
down_revision = '4eed0dfa1a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_budget', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('budget_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('schedule_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('schedule_file')
        batch_op.drop_column('budget_file')
        batch_op.drop_column('total_budget')

    # ### end Alembic commands ###
